#!/usr/bin/env bash
set -e
pushd libspectrum
./autogen.sh
./configure
sudo make install
popd
pushd fuse-emulator-for-ci
./autogen.sh
./configure --with-audio-driver=null # fuse seems to get unhappy if it's configured with audio but then can't connect to an audio service on start
sudo make install
popd
pushd sjasmplus
sudo make install
popd
