name: Test Run Solutions
on: [push]
jobs:
    test_solutions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - run: sudo apt-get install -y xonsh
            - run: env TERM=xterm LD_LIBRARY_PATH=/usr/local/lib ./run_tests
